### ISSUE TITLE
Configurable feeding source

### ISSUE THREAD

**Issue by Zergity** [nextyio/feeder#2]
For each pair of token (NUSD/USD, BTC/ETH), feeder admin can configure the price source and how its price is fed.

E.g.
config.json
"NUSD_USD": {
  "sources": {
    "binance": {
       "url": "https://api.binance.com/api/v3/ticker/price?symbol=NUSDUSDT"
    },
    "abcdex": {
       "script": "custom script to feed the price because the source does not have an url",
    }
  },
}

**Comment by techcomthanh** [comment]
Please use this file for configuration: `modules/price/config.json`
